apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretsanta-secretsanta
  labels:
    app: secretsanta
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
      matchLabels:
        app: secretsanta
    template:
        metadata:
          labels:
            app: secretsanta
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "sbhosle/santa123:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP                      